/**
 * GENERATED by art/build.py from art/lib/layout.py - do not edit (re-run `npm run art`).
 * The baked lightmaps (public/models/*_light.png) were computed with exactly this sun and these
 * tree placements, so the game must use the same values.
 */

export interface Placement {
  variant: string;
  x: number;
  z: number;
  /** Rotation about Y (degrees). */
  rotDeg: number;
  scale: number;
}

/** Unit vector toward the sun (game coordinates) and its elevation / azimuth in degrees. */
export const BAKED_SUN = {
  dir: [0.198267, 0.642788, 0.739942] as const,
  elevationDeg: 40.0,
  azimuthDeg: 15.0,
};

/** Ground lightmap rectangle (m): x0..x0+size, z0..z0+size. */
export const GROUND_LIGHT_RECT = { x0: -19.0, z0: -27.0, size: 38.0 };

export const TREES: readonly Placement[] = [
  { variant: 'c', x: 5.9, z: 6.0, rotDeg: 150.0, scale: 0.95 },
  { variant: 'a', x: 5.7, z: 1.4, rotDeg: 160.0, scale: 1.0 },
  { variant: 'b', x: 5.4, z: -3.3, rotDeg: 168.0, scale: 1.0 },
  { variant: 'a', x: 5.2, z: -8.0, rotDeg: 172.0, scale: 1.0 },
  { variant: 'c', x: 5.4, z: -12.8, rotDeg: 186.0, scale: 1.05 },
  { variant: 'b', x: -5.9, z: 5.6, rotDeg: 30.0, scale: 0.95 },
  { variant: 'c', x: -5.7, z: 1.0, rotDeg: 20.0, scale: 1.0 },
  { variant: 'a', x: -5.3, z: -3.6, rotDeg: 12.0, scale: 1.0 },
  { variant: 'c', x: -5.2, z: -7.9, rotDeg: 6.0, scale: 1.0 },
  { variant: 'b', x: -5.4, z: -12.3, rotDeg: -4.0, scale: 1.05 },
];

export const CYPRESSES: readonly Placement[] = [
  { variant: 'a', x: -5.2, z: -24.0, rotDeg: 0.0, scale: 1.05 },
  { variant: 'b', x: 7.8, z: -23.7, rotDeg: 40.0, scale: 1.1 },
  { variant: 'a', x: -12.8, z: -14.6, rotDeg: 120.0, scale: 1.0 },
  { variant: 'b', x: 12.6, z: -14.9, rotDeg: 200.0, scale: 1.0 },
  { variant: 'a', x: 18.0, z: -12.0, rotDeg: 10.0, scale: 1.1 },
  { variant: 'b', x: -18.4, z: -11.4, rotDeg: 250.0, scale: 1.0 },
];
