/**
 * Service worker registration + the "new version" flow (production builds only).
 *
 * The worker (generated by vite-plugin-pwa, see vite.config.ts) precaches the whole app, so the
 * game works offline after the first load. A new build never takes over on its own: it installs
 * in the background and waits; `onUpdate` fires, the UI offers "Update", and only `apply()`
 * tells it to activate and reloads the page. So nothing swaps under the player mid-throw.
 */

export interface UpdateWatcher {
  /** Called (once per waiting version) when a new version is installed and ready. */
  onUpdate(fn: () => void): void;
  /** Activates the waiting version, then reloads the page. */
  apply(): void;
}

/** Re-check for a new version at most this often while the app stays open (installed apps live for days). */
const RECHECK_MS = 60 * 60 * 1000;

const NOOP: UpdateWatcher = { onUpdate: () => undefined, apply: () => undefined };

export function registerServiceWorker(): UpdateWatcher {
  // Not in dev: the worker would cache stale modules and fight Vite's HMR.
  if (!import.meta.env.PROD || !('serviceWorker' in navigator)) return NOOP;

  let updateFn: () => void = () => undefined;
  let waiting: ServiceWorker | null = null;
  let announced = false;
  let applying = false;

  const announce = (worker: ServiceWorker): void => {
    waiting = worker;
    if (announced) return;
    announced = true;
    updateFn();
  };

  // The new worker took control (after apply()): load the new version's files.
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (applying) location.reload();
  });

  window.addEventListener('load', () => {
    // Relative to the page (BASE_URL is './'), so any sub-path works; the scope is the worker's folder.
    navigator.serviceWorker
      .register(`${import.meta.env.BASE_URL}sw.js`)
      .then((reg) => {
        // A previous visit may have left a version waiting.
        if (reg.waiting && navigator.serviceWorker.controller) announce(reg.waiting);
        reg.addEventListener('updatefound', () => {
          const installing = reg.installing;
          installing?.addEventListener('statechange', () => {
            // `controller` is null on the very first install: nothing to update then.
            if (installing.state === 'installed' && navigator.serviceWorker.controller) announce(installing);
          });
        });
        let lastCheck = Date.now();
        const recheck = (): void => {
          if (Date.now() - lastCheck < RECHECK_MS) return;
          lastCheck = Date.now();
          reg.update().catch(() => undefined); // offline: try again later
        };
        document.addEventListener('visibilitychange', () => {
          if (document.visibilityState === 'visible') recheck();
        });
      })
      .catch(() => undefined); // no worker: the game still works online
  });

  return {
    onUpdate(fn) {
      updateFn = fn;
      if (waiting) fn(); // announced before anyone listened
    },
    apply() {
      if (!waiting) return;
      applying = true;
      waiting.postMessage({ type: 'SKIP_WAITING' });
    },
  };
}
