"""
Scene layout shared by the light bake (lib/bake.py) and the game: the sun direction, where the
instanced trees stand, and the square of ground covered by the ground lightmap.

This is the single source of truth: the bake writes it to src/render/bakedLayout.ts (generated, do
not edit) so the game places the trees exactly where their baked shadows are, and points its
real-time sun (used for the boules' shadows and the N.L shading) along the baked sun.
"""
from __future__ import annotations

import math

# Sun: elevation above the horizon and azimuth around the court (0 = behind the player (+Z),
# 90 = from the right (+X)), degrees. Angular diameter (deg) sets the softness of the baked shadows
# (the real sun is ~0.53 deg; a little more reads softer and hides the lightmap texels).
SUN = {"elevation": 40.0, "azimuth": 15.0, "angle": 1.1}


def sun_direction() -> tuple[float, float, float]:
    """Unit vector toward the sun, game coordinates."""
    el, az = math.radians(SUN["elevation"]), math.radians(SUN["azimuth"])
    return (math.sin(az) * math.cos(el), math.sin(el), math.cos(az) * math.cos(el))


# Plane trees in two rows along the whole court, from the throwing end (z ~ +6) to the far end
# (z ~ -13), ~4.7 m apart, well off the playing area (|x| 5..6; the sides are staggered a little so
# they don't read as a grid). The models reach toward +X, so ~180 deg on the right side and ~0 deg on
# the left hang the crowns toward the court. (variant, x, z, rotation about Y in degrees, scale)
TREES = [
    # right side (+X), from the throwing end to the far end
    ("c", 5.9, 6.0, 150.0, 0.95),
    ("a", 5.7, 1.4, 160.0, 1.0),
    ("b", 5.4, -3.3, 168.0, 1.0),
    ("a", 5.2, -8.0, 172.0, 1.0),
    ("c", 5.4, -12.8, 186.0, 1.05),
    # left side (-X)
    ("b", -5.9, 5.6, 30.0, 0.95),
    ("c", -5.7, 1.0, 20.0, 1.0),
    ("a", -5.3, -3.6, 12.0, 1.0),
    ("c", -5.2, -7.9, 6.0, 1.0),
    ("b", -5.4, -12.3, -4.0, 1.05),
]

# Tall dark cypresses behind the far row of houses and in the side streets.
CYPRESSES = [
    ("a", -5.2, -24.0, 0.0, 1.05),
    ("b", 7.8, -23.7, 40.0, 1.1),
    ("a", -12.8, -14.6, 120.0, 1.0),
    ("b", 12.6, -14.9, 200.0, 1.0),
    ("a", 18.0, -12.0, 10.0, 1.1),
    ("b", -18.4, -11.4, 250.0, 1.0),
]

# Ground lightmap: a square of the village floor (x0, z0, size in m) baked into one texture,
# public/models/ground_light.png. Outside it the ground is lit as if in open sun (the countryside
# seen through the streets).
GROUND_RECT = {"x0": -19.0, "z0": -27.0, "size": 38.0}
GROUND_RES = 2048
# The court + ~2 m around it get their own, much denser sun-visibility map (court_light.webp,
# ~6 mm texels), cross-faded into the ground map at its edge: the camera is closest here.
COURT_RECT = {"x0": -4.0, "z0": -12.0, "w": 8.0, "d": 19.2}
COURT_RES = (1280, 3072)
VILLAGE_RES = 1024


def to_ts() -> str:
    """The game's copy of the layout (src/render/bakedLayout.ts)."""
    d = sun_direction()

    def rows(items):
        return "\n".join(
            f"  {{ variant: '{v}', x: {x}, z: {z}, rotDeg: {r}, scale: {s} }}," for v, x, z, r, s in items
        )

    g = GROUND_RECT
    c = COURT_RECT
    return f"""/**
 * GENERATED by art/build.py from art/lib/layout.py - do not edit (re-run `npm run art`).
 * The baked lightmaps (public/models/*_light.*) were computed with exactly this sun and these
 * tree placements, so the game must use the same values.
 */

export interface Placement {{
  variant: string;
  x: number;
  z: number;
  /** Rotation about Y (degrees). */
  rotDeg: number;
  scale: number;
}}

/** Unit vector toward the sun (game coordinates) and its elevation / azimuth in degrees. */
export const BAKED_SUN = {{
  dir: [{d[0]:.6f}, {d[1]:.6f}, {d[2]:.6f}] as const,
  elevationDeg: {SUN["elevation"]},
  azimuthDeg: {SUN["azimuth"]},
}};

/** Ground lightmap rectangle (m): x0..x0+size, z0..z0+size. */
export const GROUND_LIGHT_RECT = {{ x0: {g["x0"]}, z0: {g["z0"]}, size: {g["size"]} }};

/** High-density court sun-visibility map rectangle (m): x0..x0+w, z0..z0+d. */
export const COURT_LIGHT_RECT = {{ x0: {c["x0"]}, z0: {c["z0"]}, w: {c["w"]}, d: {c["d"]} }};

export const TREES: readonly Placement[] = [
{rows(TREES)}
];

export const CYPRESSES: readonly Placement[] = [
{rows(CYPRESSES)}
];
"""
